import { useContext, useEffect, useState } from "react"
import styles from "./image.module.css"

import Cookies from "universal-cookie"
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import { faL, faTrash } from "@fortawesome/free-solid-svg-icons"

import API from "../../utils/api"

import { ImageLoading } from "../../App"



export default function  ArtImage(props) {
    const [allData, setAllData] = useState({})
    const [generatedData, setGenData] = useState({})
    const [selected, setSelected] = useState(false)

    let imageData = allData? props.imageData : allData;
    const [imageUrl, setImageUrl] = useState(imageData.imgUrl)
    const [isVisible, setIsVisible] = useState(true)

    const {loadingState, startWorker} = useContext(ImageLoading)
    const [loading, SetLoading] = loadingState;

    let waitTimeOut;
    let countingTimeout;


    // might keep this state to show remaining time
    // TODO: replace with loading later
    const [waitTime, setWaitTime] = useState(Infinity);
    const [finalWait, setFinalWait] = useState(false);

    const cookies = new Cookies(null, { path : "/"});
    const userId= cookies.get('currentUser').id;


    const handleDelete = async (e) => {
        e.stopPropagation();
        setIsVisible(false)

        const allCookies = cookies.get('images')
        cookies.set('images', allCookies.filter((image) => {return image.id != imageData.id}))

        await API.deleteImage(imageData.id)

    }

    useEffect(()=> {
        if (!generatedData.genId){
            setGenData({"genId" : imageData.id})
        }

    }, [])


    useEffect(() => {

        // if url is not ready, wait for image
        if (props.prevImage && !imageUrl && !generatedData.id){

            const worker = startWorker()


            let options = {
                id : imageData.id,
                generateUrl : `${import.meta.env.VITE_BACKEND_URL}/generate/${imageData.id}`,
                uploadUrl : `${import.meta.env.VITE_BACKEND_URL}/generate/upload-firebase`,
                userId : userId,
                prompt : imageData.imagePrompt
            }

            if (imageData.id){
                worker.postMessage(options);
            }

            worker.onmessage = function (e) {
                if (e.data.wait_time > 0) {
                    let counter = e.data.wait_time;
                    clearInterval(countingTimeout);
                    countingTimeout = setInterval(()=> {
                        counter -= 1
                        if (counter > 0){
                            setWaitTime(counter)
                        } else {
                            clearInterval(countingTimeout)
                            worker.postMessage(options)
                        }
                    }, 1200)
                // shows image is still generated by Ai Horde
                } else if (e.data.worker_id){

                    const allData = {...generatedData, ...e.data}

                    setGenData(allData)
                    setImageUrl(e.data.imgUrl)
                    setFinalWait(!finalWait)

                } else {

                    if (generatedData.genId && e.data.imgUrl) {


                        // edits the image at the current index to the new stored firebase image
                        SetLoading(false)
                        props.removeImage(generatedData.genId, e.data)

                        // DID: Use this to fix bug when loading new image
                        setAllData(e.data)
                        imageData = e.data;


                    }



                }
            }

        }

        if (imageData.imgUrl && !props.prevImage) {
            setImageUrl(imageData.imgUrl)
        }

        if (props.selectedImages){
            if (props.selectedImages.includes(imageData)){
                setSelected(true)
            } else{
                setSelected(false)
            }
        }



    }, [imageData,finalWait,generatedData, props.selectedImages])

    if (!isVisible){
        return
    }


    return (
        <div className={styles.main_image} style={{
                backgroundImage: imageUrl? `url(${imageUrl})` : 'url("https://i0.wp.com/port2flavors.com/wp-content/uploads/2022/07/placeholder-614.png?fit=1200%2C800&ssl=1")',
                height: `${props.height? props.height : 120}px`,
                width: `${props.width? props.width : 120}px`,
                cursor: props.prevImage ? 'pointer' : 'auto',
                border: (selected && props.prevImage) ? "10px solid rgb(3, 120, 60)" : null

            }}
            onClick={() => {
                props.prevImage? props.setCurrentImage(imageData) : null;
                (props.prevImage && props.selectedImages && !selected && !imageData.wait_time)? props.setSelectedImages((prev) => {
                    if (prev.length >= 3){
                        prev.shift()
                        return [prev, imageData]
                    } else {
                        return [...prev, imageData]
                    }

                }) : null ;
                (props.prevImage && props.selectedImages && selected && !imageData.wait_time)? props.setSelectedImages((prev) => {
                    return prev.filter(item => item != imageData)
                }) : null
            }}
        >
            {
              ((waitTime) && (!imageData.imgUrl) && (waitTime != Infinity)) > 0 && (<p>{waitTime}</p>)
            }

            {(props.prevImage && (imageData.imgUrl)) && (<FontAwesomeIcon icon={faTrash} color='rgba(255, 0, 0, 0.745)'
                onClick={handleDelete}
            />)}
        </div>
    )
}
